title: roses_are_rosie
author: Gabriel Ignacio
email: gignacio611@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Gabriel Ignacio...

# social links
instagram_username: gabriel._.ignacio
github_username:  GabrielIgnacio # DO NOT include the @ character, or else the build will fail!
spotify_username: gignacioftw
steam_username: sokka

share-links-active:
  instagram_username: true
  github_username: true
  spotify_username: true
  steam_username: true
show_excerpts: true # set to false to remove excerpts on the homepage

plugins:
  - jekyll-paginate
  - jekyll-sitemap

