title: roses_are_rosie
author: Gabriel Ignacio
email: gignacio611@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Gabriel Ignacio...

# social links
instagram: gabriel._.ignacio  
github:  GabrielIgnacio # DO NOT include the @ character, or else the build will fail!
spotify: gignacioftw  
steam: sokka  
  
show_excerpts: true # set to false to remove excerpts on the homepage


